# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: EJB Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-test-matrix:
    name: ${{ matrix.jdk-distribution}}-${{ matrix.jdk-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk-distribution: [temurin]
        jdk-version: [17]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk-distribution }} ${{ matrix.jdk-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.jdk-distribution }}
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'
      - name: Prepare server
        run: mvn --batch-mode --no-transfer-progress package -DspecificModule=prepare
      - name: Run Tests
        run: mvn --batch-mode --no-transfer-progress dependency:tree clean verify --fail-at-end -Dmaven.test.redirectTestOutputToFile=true
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
          path: '**/surefire-reports/*.txt'
